---
- name: install apache packages
  apt:
    name: {{ packages }}
    state: latest
    update_cache: yes
  vars:
    packages:
      - apache2-mpm-prefork

- name: enable apache2 modules
  apache2_module: state=present name={{ item }}
  with_items:
    - expires
    - ssl
    - rewrite
