---
- name: install apache packages
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - apache2-mpm-prefork

- name: enable apache2 modules
  apache2_module: state=present name={{ item }}
  with_items:
    - expires
    - ssl
    - rewrite